server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name daugavpils.fans www.daugavpils.fans;

    ssl_certificate     /etc/letsencrypt/live/daugavpils.fans/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/daugavpils.fans/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
